import { useState, useRef } from 'react';
import { useMapart } from '../../context/MapartContext';
import { useCanvasInteraction } from '../../hooks/useCanvasInteraction';
import { type useMapartWorker } from '../../hooks/useMapartWorker';
import { CanvasStatusBar } from './canvas/CanvasStatusBar';
import { CanvasToolbar } from './canvas/CanvasToolbar';
import { ImageUploader } from './canvas/ImageUploader';
import { ManualEditsOverlay } from './canvas/ManualEditsOverlay';

interface MainCanvasProps {
    workerState: ReturnType<typeof useMapartWorker>;
}

export const MainCanvas = ({ workerState }: MainCanvasProps) => {
    const {
        uploadedImage, setUploadedImage, previewUrl, gridDimensions,
        // imageFitMode, cropSettings, buildMode, 
        selectedPaletteItems,
        // threeDPrecision, dithering, useCielab, hybridStrength,
        // setMapartStats, independentMaps, imageSettings 
        // We only need the ones used for rendering/UI, logic is in workerState
        mapartStats
    } = useMapart();

    // Use passed worker state
    const {
        isProcessing,
        scaledPreviewUrl,
        originalTransformedUrl,
        mapartResolution,
        isExporting,
        exportMapart
    } = workerState;

    const isPainting = useMapart(s => s.isPainting);
    const brushBlock = useMapart(s => s.brushBlock);
    const setManualEdit = useMapart(s => s.setManualEdit);

    const {
        scale,
        setScale,
        position,
        isDragging,
        handleWheel,
        handleMouseDown,
        handleMouseMove,
        handleMouseUp
    } = useCanvasInteraction(uploadedImage, isPainting);

    // Painting Handler
    const handlePaint = (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isPainting || !uploadedImage || !brushBlock) return;

        // Get click position relative to the image
        // We use nativeEvent.offsetX/Y which handles the scaling of the container gracefully 
        // as long as the event target is the image/overlay itself appropriately sized.

        // Note: Mapart resolution (width) is strictly `128 * grid * 128`.
        // e.nativeEvent.offsetX should be close to pixel index.
        const pixelX = Math.floor(e.nativeEvent.offsetX);
        const pixelY = Math.floor(e.nativeEvent.offsetY);

        if (pixelX >= 0 && pixelX < mapartResolution.width && pixelY >= 0 && pixelY < mapartResolution.height) {
            const index = pixelY * mapartResolution.width + pixelX;
            setManualEdit(index, brushBlock);
        }
    };

    // Function to handle mouse move for painting (drag-paint)
    const handlePaintMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (e.buttons === 1) { // Left mouse button held
            handlePaint(e);
        }
    }

    // UI State
    const [showPreview, setShowPreview] = useState(true);
    const containerRef = useRef<HTMLDivElement>(null);
    const imageRef = useRef<HTMLImageElement>(null);

    const handleExportSchematic = () => {
        if (!scaledPreviewUrl || isExporting) return;

        exportMapart(
            `mapart_${gridDimensions.x}x${gridDimensions.y}.litematic`,
            {
                author: 'mapart-creator',
                name: `MapArt ${gridDimensions.x}x${gridDimensions.y}`,
                description: `MapArt schematic generated by mapart-creator`
            }
        );
    };

    const hasSelection = Object.values(selectedPaletteItems).some(v => v !== null);

    return (
        <div
            className="flex-1 h-full relative bg-zinc-800 overflow-hidden flex flex-col"
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
        >
            {uploadedImage ? (
                <>
                    <CanvasToolbar
                        scale={scale}
                        setScale={setScale}
                        isDragging={isDragging}
                        showPreview={showPreview}
                        setShowPreview={setShowPreview}
                        onExport={handleExportSchematic}
                        canExport={!!scaledPreviewUrl && hasSelection}
                        onClearImage={() => setUploadedImage(null)}
                        isProcessing={isProcessing}
                        isExporting={isExporting}
                    />

                    <CanvasStatusBar
                        mapartResolution={mapartResolution}
                        gridDimensions={gridDimensions}
                        mapartStats={mapartStats}
                    />

                    {/* Canvas Area */}
                    <div
                        ref={containerRef}
                        className="flex-1 flex items-center justify-center overflow-hidden cursor-move bg-zinc-800 bg-[radial-gradient(#333_1px,transparent_1px)] bg-[size:20px_20px]"
                        onWheel={handleWheel}
                        onMouseDown={handleMouseDown}
                    >
                        <div
                            style={{
                                transform: `translate(${position.x}px, ${position.y}px) scale(${scale})`,
                                transition: isDragging ? 'none' : 'transform 0.1s ease-out'
                            }}
                            className="origin-center shadow-2xl flex gap-4"
                        >
                            {/* Original Image */}
                            <div className="relative">
                                <div className="absolute -top-6 left-0 text-[10px] uppercase tracking-wider text-zinc-500 font-semibold">Original</div>
                                <img
                                    ref={imageRef}
                                    src={originalTransformedUrl || previewUrl!}
                                    alt="Original"
                                    className="max-w-none pointer-events-none select-none border border-zinc-600 rendering-pixelated"
                                    draggable={false}
                                    style={{
                                        width: mapartResolution.width,
                                        height: mapartResolution.height,
                                        imageRendering: 'auto'
                                    }}
                                />
                            </div>

                            {/* Mapart Preview */}
                            {showPreview && scaledPreviewUrl && (
                                <div className="relative">
                                    {/* Painting Overlay and Visual Feedback */}
                                    {isPainting && (
                                        <>
                                            <div
                                                className="absolute inset-0 cursor-crosshair z-20"
                                                onMouseDown={handlePaint}
                                                onMouseMove={handlePaintMove}
                                                style={{
                                                    width: mapartResolution.width,
                                                    height: mapartResolution.height,
                                                }}
                                            />
                                            {/* We render manual edits on top to ensure instant feedback even if preview is updating */}
                                            <div className="absolute inset-0 z-10 pointer-events-none">
                                                <ManualEditsOverlay
                                                    width={mapartResolution.width}
                                                    height={mapartResolution.height}
                                                />
                                            </div>
                                        </>
                                    )}
                                    <div className="absolute -top-6 left-0 text-[10px] uppercase tracking-wider text-green-500 font-semibold">Mapart Preview</div>
                                    <img
                                        src={scaledPreviewUrl}
                                        alt="Mapart Preview"
                                        className="max-w-none pointer-events-none select-none border border-green-600/50 rendering-pixelated"
                                        draggable={false}
                                        style={{
                                            width: mapartResolution.width,
                                            height: mapartResolution.height,
                                            imageRendering: 'pixelated'
                                        }}
                                    />
                                    {/* Grid Overlay */}
                                    <div
                                        className="absolute inset-0 pointer-events-none"
                                        style={{
                                            backgroundImage: `
                                                linear-gradient(to right, rgba(255,255,255,0.1) 1px, transparent 1px),
                                                linear-gradient(to bottom, rgba(255,255,255,0.1) 1px, transparent 1px)
                                            `,
                                            backgroundSize: `${128}px ${128}px`
                                        }}
                                    />

                                    {/* Coordinates Overlay */}
                                    {(gridDimensions.x > 1 || gridDimensions.y > 1) && (
                                        <div className="absolute inset-0 pointer-events-none">
                                            {Array.from({ length: gridDimensions.y }).map((_, y) => (
                                                Array.from({ length: gridDimensions.x }).map((_, x) => (
                                                    <div
                                                        key={`${x}-${y}`}
                                                        className="absolute text-[10px] font-mono font-bold text-white/50 select-none flex items-start justify-start p-1"
                                                        style={{
                                                            left: x * 128,
                                                            top: y * 128,
                                                            width: 128,
                                                            height: 128,
                                                            textShadow: '0 1px 2px rgba(0,0,0,0.8)'
                                                        }}
                                                    >
                                                        {x},{y}
                                                    </div>
                                                ))
                                            ))}
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    </div>
                </>
            ) : (
                <ImageUploader
                    onUpload={setUploadedImage}
                    gridDimensions={gridDimensions}
                    mapartResolution={{
                        width: 128 * gridDimensions.x,
                        height: 128 * gridDimensions.y
                    }}
                />
            )}
        </div>
    );
};
