import { useState, useRef } from 'react';
import { useMapart } from '../../context/MapartContext';
import { downloadLitematica } from '../../utils/litematicaExport';
import { useCanvasInteraction } from '../../hooks/useCanvasInteraction';
import { useMapartWorker } from '../../hooks/useMapartWorker';
import { CanvasStatusBar } from './canvas/CanvasStatusBar';
import { CanvasToolbar } from './canvas/CanvasToolbar';
import { ImageUploader } from './canvas/ImageUploader';

export const MainCanvas = () => {
    const {
        uploadedImage, setUploadedImage, previewUrl, gridDimensions,
        imageFitMode, cropSettings, buildMode, selectedPaletteItems, threeDPrecision, dithering, useCielab, hybridStrength,
        setMapartStats, mapartStats, independentMaps, imageSettings
    } = useMapart();

    // Custom Hooks
    const {
        isProcessing,
        scaledPreviewUrl,
        originalTransformedUrl,
        mapartResolution
    } = useMapartWorker({
        uploadedImage,
        previewUrl,
        gridDimensions,
        imageFitMode,
        cropSettings,
        buildMode,
        selectedPaletteItems,
        threeDPrecision,
        dithering,
        useCielab,
        hybridStrength,
        independentMaps,
        setMapartStats,
        imageSettings
    });

    const {
        scale,
        setScale,
        position,
        isDragging,
        handleWheel,
        handleMouseDown,
        handleMouseMove,
        handleMouseUp
    } = useCanvasInteraction(uploadedImage);

    // UI State
    const [showPreview, setShowPreview] = useState(true);
    const containerRef = useRef<HTMLDivElement>(null);
    const imageRef = useRef<HTMLImageElement>(null);

    const handleExportSchematic = () => {
        if (!scaledPreviewUrl) return;

        const img = new Image();
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            if (!ctx) return;

            ctx.drawImage(img, 0, 0);
            const imageData = ctx.getImageData(0, 0, img.width, img.height);

            downloadLitematica(
                imageData,
                selectedPaletteItems,
                buildMode,
                `mapart_${gridDimensions.x}x${gridDimensions.y}.litematic`,
                {
                    author: 'mapart-creator',
                    name: `MapArt ${gridDimensions.x}x${gridDimensions.y}`,
                    description: `MapArt schematic generated by mapart-creator`
                },
                threeDPrecision,
                useCielab,
                hybridStrength,
                independentMaps
            );
        };
        img.src = scaledPreviewUrl;
    };

    const hasSelection = Object.values(selectedPaletteItems).some(v => v !== null);

    return (
        <div
            className="flex-1 h-full relative bg-zinc-800 overflow-hidden flex flex-col"
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
        >
            {uploadedImage ? (
                <>
                    <CanvasToolbar
                        scale={scale}
                        setScale={setScale}
                        isDragging={isDragging}
                        showPreview={showPreview}
                        setShowPreview={setShowPreview}
                        onExport={handleExportSchematic}
                        canExport={!!scaledPreviewUrl && hasSelection}
                        onClearImage={() => setUploadedImage(null)}
                        isProcessing={isProcessing}
                    />

                    <CanvasStatusBar
                        mapartResolution={mapartResolution}
                        gridDimensions={gridDimensions}
                        mapartStats={mapartStats}
                    />

                    {/* Canvas Area */}
                    <div
                        ref={containerRef}
                        className="flex-1 flex items-center justify-center overflow-hidden cursor-move bg-zinc-800 bg-[radial-gradient(#333_1px,transparent_1px)] bg-[size:20px_20px]"
                        onWheel={handleWheel}
                        onMouseDown={handleMouseDown}
                    >
                        <div
                            style={{
                                transform: `translate(${position.x}px, ${position.y}px) scale(${scale})`,
                                transition: isDragging ? 'none' : 'transform 0.1s ease-out'
                            }}
                            className="origin-center shadow-2xl flex gap-4"
                        >
                            {/* Original Image */}
                            <div className="relative">
                                <div className="absolute -top-6 left-0 text-[10px] uppercase tracking-wider text-zinc-500 font-semibold">Original</div>
                                <img
                                    ref={imageRef}
                                    src={originalTransformedUrl || previewUrl!}
                                    alt="Original"
                                    className="max-w-none pointer-events-none select-none border border-zinc-600 rendering-pixelated"
                                    draggable={false}
                                    style={{
                                        width: mapartResolution.width,
                                        height: mapartResolution.height,
                                        imageRendering: 'auto'
                                    }}
                                />
                            </div>

                            {/* Mapart Preview */}
                            {showPreview && scaledPreviewUrl && (
                                <div className="relative">
                                    <div className="absolute -top-6 left-0 text-[10px] uppercase tracking-wider text-green-500 font-semibold">Mapart Preview</div>
                                    <img
                                        src={scaledPreviewUrl}
                                        alt="Mapart Preview"
                                        className="max-w-none pointer-events-none select-none border border-green-600/50 rendering-pixelated"
                                        draggable={false}
                                        style={{
                                            width: mapartResolution.width,
                                            height: mapartResolution.height,
                                            imageRendering: 'pixelated'
                                        }}
                                    />
                                    {/* Grid Overlay */}
                                    <div
                                        className="absolute inset-0 pointer-events-none"
                                        style={{
                                            backgroundImage: `
                                                linear-gradient(to right, rgba(255,255,255,0.1) 1px, transparent 1px),
                                                linear-gradient(to bottom, rgba(255,255,255,0.1) 1px, transparent 1px)
                                            `,
                                            backgroundSize: `${128}px ${128}px`
                                        }}
                                    />
                                </div>
                            )}
                        </div>
                    </div>
                </>
            ) : (
                <ImageUploader
                    onUpload={setUploadedImage}
                    gridDimensions={gridDimensions}
                    mapartResolution={{
                        width: 128 * gridDimensions.x,
                        height: 128 * gridDimensions.y
                    }}
                />
            )}
        </div>
    );
};
