import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useCanvasActions } from '../useCanvasActions';

describe('useCanvasActions', () => {
    const mockExportMapart = vi.fn();
    const mockWorkerImageData = new ImageData(new Uint8ClampedArray([255, 0, 0, 255]), 1, 1);

    const defaultProps = {
        isExporting: false,
        exportFormat: 'litematic' as const,
        gridDimensions: { x: 1, y: 1 },
        exportMode: 'full' as const,
        exportMapart: mockExportMapart,
        workerImageData: mockWorkerImageData
    };

    beforeEach(() => {
        vi.clearAllMocks();
        vi.useFakeTimers();
    });

    afterEach(() => {
        vi.useRealTimers();
    });

    describe('handleExportSchematic', () => {
        it('calls exportMapart with correct filename and metadata', async () => {
            vi.useRealTimers();
            const { result } = renderHook(() => useCanvasActions(defaultProps));

            await act(async () => {
                await result.current.handleExportSchematic();
            });

            expect(mockExportMapart).toHaveBeenCalledWith(
                'mapart_1x1.litematic',
                expect.objectContaining({
                    author: 'MapArtisan',
                    name: 'Map Art 1x1',
                    description: 'Map Art schematic generated by MapArtisan'
                })
            );
            vi.useFakeTimers();
        });

        it('uses .nbt extension when exportFormat is nbt', async () => {
            vi.useRealTimers();
            const { result } = renderHook(() => useCanvasActions({
                ...defaultProps,
                exportFormat: 'nbt'
            }));

            await act(async () => {
                await result.current.handleExportSchematic();
            });

            expect(mockExportMapart).toHaveBeenCalledWith(
                'mapart_1x1.nbt',
                expect.any(Object)
            );
            vi.useFakeTimers();
        });

        it('does not call exportMapart when workerImageData is null', async () => {
            const { result } = renderHook(() => useCanvasActions({
                ...defaultProps,
                workerImageData: null
            }));

            await act(async () => {
                await result.current.handleExportSchematic();
            });

            expect(mockExportMapart).not.toHaveBeenCalled();
        });

        it('does not call exportMapart when isExporting is true', async () => {
            const { result } = renderHook(() => useCanvasActions({
                ...defaultProps,
                isExporting: true
            }));

            await act(async () => {
                await result.current.handleExportSchematic();
            });

            expect(mockExportMapart).not.toHaveBeenCalled();
        });

        it('uses correct grid dimensions in filename', async () => {
            vi.useRealTimers();
            const { result } = renderHook(() => useCanvasActions({
                ...defaultProps,
                gridDimensions: { x: 3, y: 2 }
            }));

            await act(async () => {
                await result.current.handleExportSchematic();
            });

            expect(mockExportMapart).toHaveBeenCalledWith(
                'mapart_3x2.litematic',
                expect.any(Object)
            );
            vi.useFakeTimers();
        });
    });

    describe('handleDownloadPreview', () => {
        it('does nothing when workerImageData is null', async () => {
            const { result } = renderHook(() => useCanvasActions({
                ...defaultProps,
                workerImageData: null
            }));

            await act(async () => {
                await result.current.handleDownloadPreview();
            });
        });

        it('creates download link from ImageData on demand', async () => {
            const { result } = renderHook(() => useCanvasActions(defaultProps));

            await act(async () => {
                await result.current.handleDownloadPreview();
            });
        });
    });

    describe('handleToggle3D', () => {
        it('toggles is3DMode state', () => {
            const { result } = renderHook(() => useCanvasActions(defaultProps));

            expect(result.current.is3DMode).toBe(false);

            act(() => {
                result.current.handleToggle3D();
            });

            expect(result.current.is3DMode).toBe(true);

            act(() => {
                result.current.handleToggle3D();
            });

            expect(result.current.is3DMode).toBe(false);
        });

        it('sets debounced3DImageData when entering 3D mode', () => {
            const { result } = renderHook(() => useCanvasActions(defaultProps));

            act(() => {
                result.current.handleToggle3D();
            });

            expect(result.current.debounced3DImageData).toBe(mockWorkerImageData);
        });

        it('releases debounced3DImageData when exiting 3D mode', () => {
            const { result } = renderHook(() => useCanvasActions(defaultProps));

            act(() => {
                result.current.handleToggle3D(); // Enter 3D
            });

            act(() => {
                result.current.handleToggle3D(); // Exit 3D
            });

            expect(result.current.debounced3DImageData).toBeNull();
        });
    });

    describe('3D image debounce', () => {
        it('debounces workerImageData updates by 150ms', () => {
            const { result, rerender } = renderHook(
                (props) => useCanvasActions(props),
                { initialProps: defaultProps }
            );

            act(() => {
                result.current.handleToggle3D();
            });

            const newImageData = new ImageData(new Uint8ClampedArray([0, 255, 0, 255]), 1, 1);

            rerender({
                ...defaultProps,
                workerImageData: newImageData
            });

            // Before debounce
            expect(result.current.debounced3DImageData).toBe(mockWorkerImageData);

            // After debounce
            act(() => {
                vi.advanceTimersByTime(150);
            });

            expect(result.current.debounced3DImageData).toBe(newImageData);
        });

        it('does not update when not in 3D mode', () => {
            const { result, rerender } = renderHook(
                (props) => useCanvasActions(props),
                { initialProps: defaultProps }
            );

            const newImageData = new ImageData(new Uint8ClampedArray([0, 255, 0, 255]), 1, 1);

            rerender({
                ...defaultProps,
                workerImageData: newImageData
            });

            act(() => {
                vi.advanceTimersByTime(150);
            });

            expect(result.current.debounced3DImageData).toBeNull();
        });
    });

    describe('snapshot regression', () => {
        it('produces consistent state structure', () => {
            const { result } = renderHook(() => useCanvasActions(defaultProps));

            act(() => {
                result.current.handleToggle3D();
            });

            expect({
                is3DMode: result.current.is3DMode,
                debounced3DImageData: result.current.debounced3DImageData ? {
                    width: result.current.debounced3DImageData.width,
                    height: result.current.debounced3DImageData.height
                } : null
            }).toMatchSnapshot();
        });
    });
});
