import { useState, useRef, useEffect, useCallback } from 'react';
import type { GridDimensions } from '../store/useMapartStore';
import type { ExportFormat } from '../types/mapart';

interface UseCanvasActionsProps {
    scaledPreviewUrl: string | null;
    isExporting: boolean;
    exportFormat: ExportFormat;
    gridDimensions: GridDimensions;
    exportMapart: (filename: string, metadata: Record<string, unknown>) => void;
    workerImageData: ImageData | null;
}

/**
 * Hook para manejar acciones del canvas: export, download preview, y 3D mode toggle.
 * 
 * Extrae la lógica de negocio de MainCanvas.tsx para mejorar la separación de responsabilidades.
 */
export const useCanvasActions = ({
    scaledPreviewUrl,
    isExporting,
    exportFormat,
    gridDimensions,
    exportMapart,
    workerImageData
}: UseCanvasActionsProps) => {
    const [is3DMode, setIs3DMode] = useState(false);
    const [debounced3DImageData, setDebounced3DImageData] = useState<ImageData | null>(null);
    const debounce3DRef = useRef<number | null>(null);

    const handleToggle3D = useCallback(() => {
        if (!is3DMode && workerImageData) {
            setDebounced3DImageData(workerImageData);
        }
        setIs3DMode(prev => !prev);
    }, [is3DMode, workerImageData]);

    // Debounce updates while in 3D mode
    useEffect(() => {
        if (!is3DMode || !workerImageData) return;

        if (debounce3DRef.current !== null) {
            clearTimeout(debounce3DRef.current);
        }

        debounce3DRef.current = window.setTimeout(() => {
            setDebounced3DImageData(workerImageData);
        }, 150);

        return () => {
            if (debounce3DRef.current !== null) {
                clearTimeout(debounce3DRef.current);
            }
        };
    }, [workerImageData, is3DMode]);

    const handleExportSchematic = useCallback(() => {
        if (!scaledPreviewUrl || isExporting) return;

        const extension = exportFormat === 'nbt' ? '.nbt' : '.litematic';
        exportMapart(
            `mapart_${gridDimensions.x}x${gridDimensions.y}${extension}`,
            {
                author: 'MapArtisan',
                name: `Map Art ${gridDimensions.x}x${gridDimensions.y}`,
                description: `Map Art schematic generated by MapArtisan`
            }
        );
    }, [scaledPreviewUrl, isExporting, exportFormat, gridDimensions, exportMapart]);

    const handleDownloadPreview = useCallback(() => {
        if (!scaledPreviewUrl) return;
        const link = document.createElement('a');
        link.href = scaledPreviewUrl;
        link.download = `mapart_preview_${gridDimensions.x}x${gridDimensions.y}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }, [scaledPreviewUrl, gridDimensions]);

    return {
        is3DMode,
        debounced3DImageData,
        handleToggle3D,
        handleExportSchematic,
        handleDownloadPreview
    };
};
