import { useState, useRef, useEffect, useCallback } from 'react';
import type { GridDimensions } from '../store/useMapartStore';
import type { ExportFormat } from '../types/mapart';

interface UseCanvasActionsProps {
    isExporting: boolean;
    exportFormat: ExportFormat;
    gridDimensions: GridDimensions;
    exportMode: 'full' | 'sections';
    exportMapart: (filename: string, metadata: Record<string, unknown>) => void;
    workerImageData: ImageData | null;
}

function imageDataToPngBlob(imageData: ImageData): Promise<Blob> {
    const canvas = document.createElement('canvas');
    canvas.width = imageData.width;
    canvas.height = imageData.height;
    const ctx = canvas.getContext('2d')!;
    ctx.putImageData(imageData, 0, 0);
    return new Promise<Blob>((resolve, reject) => {
        canvas.toBlob(blob => {
            if (blob) resolve(blob);
            else reject(new Error('Failed to encode preview'));
        }, 'image/png');
    });
}

function imageDataToBase64Png(imageData: ImageData): Promise<string> {
    return imageDataToPngBlob(imageData).then((blob) => new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => {
            const result = reader.result as string;
            resolve(result.split(',')[1]);
        };
        reader.onerror = reject;
        reader.readAsDataURL(blob);
    }));
}

function cropImageData(source: ImageData, sx: number, sy: number, w: number, h: number): ImageData {
    const result = new ImageData(w, h);
    for (let y = 0; y < h; y++) {
        for (let x = 0; x < w; x++) {
            const srcIdx = ((sy + y) * source.width + (sx + x)) * 4;
            const dstIdx = (y * w + x) * 4;
            result.data[dstIdx] = source.data[srcIdx];
            result.data[dstIdx + 1] = source.data[srcIdx + 1];
            result.data[dstIdx + 2] = source.data[srcIdx + 2];
            result.data[dstIdx + 3] = source.data[srcIdx + 3];
        }
    }
    return result;
}

/**
 * Hook para manejar acciones del canvas: export, download preview, y 3D mode toggle.
 * 
 * Extrae la lógica de negocio de MainCanvas.tsx para mejorar la separación de responsabilidades.
 */
export const useCanvasActions = ({
    isExporting,
    exportFormat,
    gridDimensions,
    exportMode,
    exportMapart,
    workerImageData
}: UseCanvasActionsProps) => {
    const [is3DMode, setIs3DMode] = useState(false);
    const [debounced3DImageData, setDebounced3DImageData] = useState<ImageData | null>(null);
    const debounce3DRef = useRef<number | null>(null);

    const handleToggle3D = useCallback(() => {
        if (!is3DMode && workerImageData) {
            setDebounced3DImageData(workerImageData);
        } else if (is3DMode) {
            setDebounced3DImageData(null);
        }
        setIs3DMode(prev => !prev);
    }, [is3DMode, workerImageData]);

    // Debounce updates while in 3D mode
    useEffect(() => {
        if (!is3DMode || !workerImageData) {
            if (debounce3DRef.current !== null) {
                clearTimeout(debounce3DRef.current);
                debounce3DRef.current = null;
            }
            return;
        }

        if (debounce3DRef.current !== null) {
            clearTimeout(debounce3DRef.current);
        }

        debounce3DRef.current = window.setTimeout(() => {
            setDebounced3DImageData(workerImageData);
            debounce3DRef.current = null;
        }, 150);

        return () => {
            if (debounce3DRef.current !== null) {
                clearTimeout(debounce3DRef.current);
            }
        };
    }, [workerImageData, is3DMode]);

    const handleExportSchematic = useCallback(async () => {
        if (!workerImageData || isExporting) return;

        const extension = exportFormat === 'nbt' ? '.nbt' : '.litematic';
        const metadata: Record<string, unknown> = {
            author: 'MapArtisan',
            name: `Map Art ${gridDimensions.x}x${gridDimensions.y}`,
            description: `Map Art schematic generated by MapArtisan`
        };

        if (exportFormat === 'litematic' && workerImageData) {
            const mapsX = gridDimensions.x;
            const mapsY = gridDimensions.y;
            const isMultiMap = (mapsX > 1 || mapsY > 1) && exportMode === 'sections';

            if (isMultiMap) {
                const sectionPreviews: Record<string, string> = {};
                for (let sy = 0; sy < mapsY; sy++) {
                    for (let sx = 0; sx < mapsX; sx++) {
                        const cropped = cropImageData(workerImageData, sx * 128, sy * 128, 128, 128);
                        sectionPreviews[`${sx}_${sy}`] = await imageDataToBase64Png(cropped);
                    }
                }
                metadata.sectionPreviews = sectionPreviews;
            } else {
                metadata.previewImageBase64 = await imageDataToBase64Png(workerImageData);
            }
        }

        exportMapart(
            `mapart_${gridDimensions.x}x${gridDimensions.y}${extension}`,
            metadata
        );
    }, [isExporting, exportFormat, exportMode, gridDimensions, workerImageData, exportMapart]);

    const handleDownloadPreview = useCallback(async () => {
        if (!workerImageData) return;
        const blob = await imageDataToPngBlob(workerImageData);
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `mapart_preview_${gridDimensions.x}x${gridDimensions.y}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, [workerImageData, gridDimensions]);

    return {
        is3DMode,
        debounced3DImageData,
        handleToggle3D,
        handleExportSchematic,
        handleDownloadPreview
    };
};
