[package]
name = "processing-wasm"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
processing-core = { path = "../processing-core" }
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-rayon = { version = "1.3", optional = true }

[features]
parallel = ["processing-core/parallel", "dep:wasm-bindgen-rayon"]
