import fs from "fs";
import path from "path";

// Block version mapping based on Minecraft version history
// Reference: https://minecraft.wiki/w/Java_Edition_version_history
const blockVersions: Record<string, string> = {
    // ========== 1.0.0 Legacy Blocks (Alpha/Beta/Full Release) ==========
    "minecraft:stone": "1.0.0",
    "minecraft:grass_block": "1.0.0",
    "minecraft:dirt": "1.0.0",
    "minecraft:cobblestone": "1.0.0",
    "minecraft:oak_planks": "1.0.0",
    "minecraft:spruce_planks": "1.0.0",
    "minecraft:birch_planks": "1.0.0",
    "minecraft:oak_log": "1.0.0",
    "minecraft:spruce_log": "1.0.0",
    "minecraft:birch_log": "1.0.0",
    "minecraft:oak_leaves": "1.0.0",
    "minecraft:spruce_leaves": "1.0.0",
    "minecraft:birch_leaves": "1.0.0",
    "minecraft:sand": "1.0.0",
    "minecraft:gravel": "1.0.0",
    "minecraft:gold_ore": "1.0.0",
    "minecraft:iron_ore": "1.0.0",
    "minecraft:coal_ore": "1.0.0",
    "minecraft:oak_wood": "1.0.0",
    "minecraft:spruce_wood": "1.0.0",
    "minecraft:birch_wood": "1.0.0",
    "minecraft:sponge": "1.0.0",
    "minecraft:glass": "1.0.0",
    "minecraft:lapis_ore": "1.0.0",
    "minecraft:lapis_block": "1.0.0",
    "minecraft:dispenser": "1.0.0",
    "minecraft:sandstone": "1.0.0",
    "minecraft:note_block": "1.0.0",
    "minecraft:white_wool": "1.0.0",
    "minecraft:orange_wool": "1.0.0",
    "minecraft:magenta_wool": "1.0.0",
    "minecraft:light_blue_wool": "1.0.0",
    "minecraft:yellow_wool": "1.0.0",
    "minecraft:lime_wool": "1.0.0",
    "minecraft:pink_wool": "1.0.0",
    "minecraft:gray_wool": "1.0.0",
    "minecraft:light_gray_wool": "1.0.0",
    "minecraft:cyan_wool": "1.0.0",
    "minecraft:purple_wool": "1.0.0",
    "minecraft:blue_wool": "1.0.0",
    "minecraft:brown_wool": "1.0.0",
    "minecraft:green_wool": "1.0.0",
    "minecraft:red_wool": "1.0.0",
    "minecraft:black_wool": "1.0.0",
    "minecraft:gold_block": "1.0.0",
    "minecraft:iron_block": "1.0.0",
    "minecraft:stone_slab": "1.0.0",
    "minecraft:sandstone_slab": "1.0.0",
    "minecraft:cobblestone_slab": "1.0.0",
    "minecraft:brick_slab": "1.0.0",
    "minecraft:stone_brick_slab": "1.0.0",
    "minecraft:bricks": "1.0.0",
    "minecraft:tnt": "1.0.0",
    "minecraft:bookshelf": "1.0.0",
    "minecraft:mossy_cobblestone": "1.0.0",
    "minecraft:obsidian": "1.0.0",
    "minecraft:spawner": "1.0.0",
    "minecraft:diamond_ore": "1.0.0",
    "minecraft:diamond_block": "1.0.0",
    "minecraft:crafting_table": "1.0.0",
    "minecraft:furnace": "1.0.0",
    "minecraft:stone_pressure_plate": "1.0.0",
    "minecraft:redstone_ore": "1.0.0",
    "minecraft:redstone_block": "1.0.0",
    "minecraft:snow_block": "1.0.0",
    "minecraft:ice": "1.0.0",
    "minecraft:clay": "1.0.0",
    "minecraft:jukebox": "1.0.0",
    "minecraft:pumpkin": "1.0.0",
    "minecraft:netherrack": "1.0.0",
    "minecraft:soul_sand": "1.0.0",
    "minecraft:glowstone": "1.0.0",
    "minecraft:carved_pumpkin": "1.0.0",
    "minecraft:jack_o_lantern": "1.0.0",
    "minecraft:stone_bricks": "1.0.0",
    "minecraft:mossy_stone_bricks": "1.0.0",
    "minecraft:cracked_stone_bricks": "1.0.0",
    "minecraft:chiseled_stone_bricks": "1.0.0",
    "minecraft:brown_mushroom_block": "1.0.0",
    "minecraft:red_mushroom_block": "1.0.0",
    "minecraft:mushroom_stem": "1.0.0",
    "minecraft:melon": "1.0.0",
    "minecraft:vine": "1.0.0",
    "minecraft:mycelium": "1.0.0",
    "minecraft:nether_bricks": "1.0.0",
    "minecraft:nether_brick_slab": "1.0.0",
    "minecraft:end_stone": "1.0.0",
    "minecraft:oak_slab": "1.0.0",
    "minecraft:spruce_slab": "1.0.0",
    "minecraft:birch_slab": "1.0.0",
    "minecraft:cobweb": "1.0.0",
    "minecraft:bedrock": "1.0.0",
    "minecraft:oak_pressure_plate": "1.0.0",
    "minecraft:spruce_pressure_plate": "1.0.0",
    "minecraft:birch_pressure_plate": "1.0.0",
    "minecraft:tall_grass": "1.0.0",
    "minecraft:piston": "1.0.0",
    "minecraft:sticky_piston": "1.0.0",
    "minecraft:infested_stone": "1.0.0",
    "minecraft:infested_cobblestone": "1.0.0",
    "minecraft:infested_stone_bricks": "1.0.0",
    "minecraft:infested_mossy_stone_bricks": "1.0.0",
    "minecraft:infested_cracked_stone_bricks": "1.0.0",
    "minecraft:infested_chiseled_stone_bricks": "1.0.0",

    // ========== 1.2.1 ==========
    "minecraft:redstone_lamp": "1.2.1",
    "minecraft:jungle_slab": "1.2.1",
    "minecraft:jungle_pressure_plate": "1.2.1",
    "minecraft:chiseled_sandstone": "1.2.1",
    "minecraft:jungle_log": "1.2.1",
    "minecraft:jungle_leaves": "1.2.1",
    "minecraft:jungle_planks": "1.2.1",

    // ========== 1.3.1 ==========
    "minecraft:emerald_ore": "1.3.1",
    "minecraft:emerald_block": "1.3.1",

    // ========== 1.4.2 ==========
    "minecraft:command_block": "1.4.2",
    "minecraft:beacon": "1.4.2",

    // ========== 1.5.0 ==========
    "minecraft:dropper": "1.5.0",
    "minecraft:quartz_block": "1.5.0",
    "minecraft:chiseled_quartz_block": "1.5.0",
    "minecraft:quartz_pillar": "1.5.0",
    "minecraft:quartz_slab": "1.5.0",
    "minecraft:nether_quartz_ore": "1.5.0",
    "minecraft:light_weighted_pressure_plate": "1.5.0",
    "minecraft:heavy_weighted_pressure_plate": "1.5.0",

    // ========== 1.6.1 ==========
    "minecraft:white_carpet": "1.6.1",
    "minecraft:orange_carpet": "1.6.1",
    "minecraft:magenta_carpet": "1.6.1",
    "minecraft:light_blue_carpet": "1.6.1",
    "minecraft:yellow_carpet": "1.6.1",
    "minecraft:lime_carpet": "1.6.1",
    "minecraft:pink_carpet": "1.6.1",
    "minecraft:gray_carpet": "1.6.1",
    "minecraft:light_gray_carpet": "1.6.1",
    "minecraft:cyan_carpet": "1.6.1",
    "minecraft:purple_carpet": "1.6.1",
    "minecraft:blue_carpet": "1.6.1",
    "minecraft:brown_carpet": "1.6.1",
    "minecraft:green_carpet": "1.6.1",
    "minecraft:red_carpet": "1.6.1",
    "minecraft:black_carpet": "1.6.1",
    "minecraft:white_terracotta": "1.6.1",
    "minecraft:orange_terracotta": "1.6.1",
    "minecraft:magenta_terracotta": "1.6.1",
    "minecraft:light_blue_terracotta": "1.6.1",
    "minecraft:yellow_terracotta": "1.6.1",
    "minecraft:lime_terracotta": "1.6.1",
    "minecraft:pink_terracotta": "1.6.1",
    "minecraft:gray_terracotta": "1.6.1",
    "minecraft:light_gray_terracotta": "1.6.1",
    "minecraft:cyan_terracotta": "1.6.1",
    "minecraft:purple_terracotta": "1.6.1",
    "minecraft:blue_terracotta": "1.6.1",
    "minecraft:brown_terracotta": "1.6.1",
    "minecraft:green_terracotta": "1.6.1",
    "minecraft:red_terracotta": "1.6.1",
    "minecraft:black_terracotta": "1.6.1",
    "minecraft:terracotta": "1.6.1",
    "minecraft:hay_block": "1.6.1",
    "minecraft:coal_block": "1.6.1",

    // ========== 1.7.2 ==========
    "minecraft:white_stained_glass": "1.7.2",
    "minecraft:orange_stained_glass": "1.7.2",
    "minecraft:magenta_stained_glass": "1.7.2",
    "minecraft:light_blue_stained_glass": "1.7.2",
    "minecraft:yellow_stained_glass": "1.7.2",
    "minecraft:lime_stained_glass": "1.7.2",
    "minecraft:pink_stained_glass": "1.7.2",
    "minecraft:gray_stained_glass": "1.7.2",
    "minecraft:light_gray_stained_glass": "1.7.2",
    "minecraft:cyan_stained_glass": "1.7.2",
    "minecraft:purple_stained_glass": "1.7.2",
    "minecraft:blue_stained_glass": "1.7.2",
    "minecraft:brown_stained_glass": "1.7.2",
    "minecraft:green_stained_glass": "1.7.2",
    "minecraft:red_stained_glass": "1.7.2",
    "minecraft:black_stained_glass": "1.7.2",
    "minecraft:large_fern": "1.7.2",
    "minecraft:sunflower": "1.7.2",
    "minecraft:lilac": "1.7.2",
    "minecraft:rose_bush": "1.7.2",
    "minecraft:peony": "1.7.2",
    "minecraft:acacia_log": "1.7.2",
    "minecraft:acacia_planks": "1.7.2",
    "minecraft:acacia_slab": "1.7.2",
    "minecraft:acacia_leaves": "1.7.2",
    "minecraft:dark_oak_log": "1.7.2",
    "minecraft:dark_oak_planks": "1.7.2",
    "minecraft:dark_oak_slab": "1.7.2",
    "minecraft:dark_oak_leaves": "1.7.2",
    "minecraft:podzol": "1.7.2",
    "minecraft:coarse_dirt": "1.7.2",
    "minecraft:red_sand": "1.7.2",
    "minecraft:packed_ice": "1.7.2",

    // ========== 1.8.0 ==========
    "minecraft:red_sandstone": "1.8.0",
    "minecraft:chiseled_red_sandstone": "1.8.0",
    "minecraft:red_sandstone_slab": "1.8.0",
    "minecraft:wet_sponge": "1.8.0",
    "minecraft:slime_block": "1.8.0",
    "minecraft:prismarine": "1.8.0",
    "minecraft:prismarine_bricks": "1.8.0",
    "minecraft:dark_prismarine": "1.8.0",
    "minecraft:sea_lantern": "1.8.0",
    "minecraft:diorite": "1.8.0",
    "minecraft:polished_diorite": "1.8.0",
    "minecraft:andesite": "1.8.0",
    "minecraft:polished_andesite": "1.8.0",
    "minecraft:granite": "1.8.0",
    "minecraft:polished_granite": "1.8.0",

    // ========== 1.9.0 ==========
    "minecraft:purpur_block": "1.9.0",
    "minecraft:purpur_pillar": "1.9.0",
    "minecraft:purpur_slab": "1.9.0",
    "minecraft:end_stone_bricks": "1.9.0",
    "minecraft:chorus_flower": "1.9.0",
    "minecraft:frosted_ice": "1.9.0",
    "minecraft:chain_command_block": "1.9.0",
    "minecraft:repeating_command_block": "1.9.0",
    "minecraft:structure_block": "1.9.0",
    "minecraft:end_gateway": "1.9.0",

    // ========== 1.10.0 ==========
    "minecraft:magma_block": "1.10.0",
    "minecraft:nether_wart_block": "1.10.0",
    "minecraft:red_nether_bricks": "1.10.0",
    "minecraft:bone_block": "1.10.0",

    // ========== 1.11.0 ==========
    "minecraft:shulker_box": "1.11.0",
    "minecraft:white_shulker_box": "1.11.0",
    "minecraft:orange_shulker_box": "1.11.0",
    "minecraft:magenta_shulker_box": "1.11.0",
    "minecraft:light_blue_shulker_box": "1.11.0",
    "minecraft:yellow_shulker_box": "1.11.0",
    "minecraft:lime_shulker_box": "1.11.0",
    "minecraft:pink_shulker_box": "1.11.0",
    "minecraft:gray_shulker_box": "1.11.0",
    "minecraft:light_gray_shulker_box": "1.11.0",
    "minecraft:cyan_shulker_box": "1.11.0",
    "minecraft:purple_shulker_box": "1.11.0",
    "minecraft:blue_shulker_box": "1.11.0",
    "minecraft:brown_shulker_box": "1.11.0",
    "minecraft:green_shulker_box": "1.11.0",
    "minecraft:red_shulker_box": "1.11.0",
    "minecraft:black_shulker_box": "1.11.0",
    "minecraft:observer": "1.11.0",

    // ========== 1.12.0 ==========
    "minecraft:white_concrete": "1.12.0",
    "minecraft:orange_concrete": "1.12.0",
    "minecraft:magenta_concrete": "1.12.0",
    "minecraft:light_blue_concrete": "1.12.0",
    "minecraft:yellow_concrete": "1.12.0",
    "minecraft:lime_concrete": "1.12.0",
    "minecraft:pink_concrete": "1.12.0",
    "minecraft:gray_concrete": "1.12.0",
    "minecraft:light_gray_concrete": "1.12.0",
    "minecraft:cyan_concrete": "1.12.0",
    "minecraft:purple_concrete": "1.12.0",
    "minecraft:blue_concrete": "1.12.0",
    "minecraft:brown_concrete": "1.12.0",
    "minecraft:green_concrete": "1.12.0",
    "minecraft:red_concrete": "1.12.0",
    "minecraft:black_concrete": "1.12.0",
    "minecraft:white_concrete_powder": "1.12.0",
    "minecraft:orange_concrete_powder": "1.12.0",
    "minecraft:magenta_concrete_powder": "1.12.0",
    "minecraft:light_blue_concrete_powder": "1.12.0",
    "minecraft:yellow_concrete_powder": "1.12.0",
    "minecraft:lime_concrete_powder": "1.12.0",
    "minecraft:pink_concrete_powder": "1.12.0",
    "minecraft:gray_concrete_powder": "1.12.0",
    "minecraft:light_gray_concrete_powder": "1.12.0",
    "minecraft:cyan_concrete_powder": "1.12.0",
    "minecraft:purple_concrete_powder": "1.12.0",
    "minecraft:blue_concrete_powder": "1.12.0",
    "minecraft:brown_concrete_powder": "1.12.0",
    "minecraft:green_concrete_powder": "1.12.0",
    "minecraft:red_concrete_powder": "1.12.0",
    "minecraft:black_concrete_powder": "1.12.0",
    "minecraft:white_glazed_terracotta": "1.12.0",
    "minecraft:orange_glazed_terracotta": "1.12.0",
    "minecraft:magenta_glazed_terracotta": "1.12.0",
    "minecraft:light_blue_glazed_terracotta": "1.12.0",
    "minecraft:yellow_glazed_terracotta": "1.12.0",
    "minecraft:lime_glazed_terracotta": "1.12.0",
    "minecraft:pink_glazed_terracotta": "1.12.0",
    "minecraft:gray_glazed_terracotta": "1.12.0",
    "minecraft:light_gray_glazed_terracotta": "1.12.0",
    "minecraft:cyan_glazed_terracotta": "1.12.0",
    "minecraft:purple_glazed_terracotta": "1.12.0",
    "minecraft:blue_glazed_terracotta": "1.12.0",
    "minecraft:brown_glazed_terracotta": "1.12.0",
    "minecraft:green_glazed_terracotta": "1.12.0",
    "minecraft:red_glazed_terracotta": "1.12.0",
    "minecraft:black_glazed_terracotta": "1.12.0",

    // ========== 1.13.0 ==========
    "minecraft:cut_sandstone": "1.13.0",
    "minecraft:jungle_wood": "1.13.0",
    "minecraft:acacia_wood": "1.13.0",
    "minecraft:dark_oak_wood": "1.13.0",
    "minecraft:acacia_pressure_plate": "1.13.0",
    "minecraft:dark_oak_pressure_plate": "1.13.0",
    "minecraft:cut_red_sandstone": "1.13.0",
    "minecraft:prismarine_slab": "1.13.0",
    "minecraft:prismarine_brick_slab": "1.13.0",
    "minecraft:dark_prismarine_slab": "1.13.0",
    "minecraft:blue_ice": "1.13.0",
    "minecraft:tube_coral_block": "1.13.0",
    "minecraft:brain_coral_block": "1.13.0",
    "minecraft:bubble_coral_block": "1.13.0",
    "minecraft:fire_coral_block": "1.13.0",
    "minecraft:horn_coral_block": "1.13.0",
    "minecraft:dead_tube_coral_block": "1.13.0",
    "minecraft:dead_brain_coral_block": "1.13.0",
    "minecraft:dead_bubble_coral_block": "1.13.0",
    "minecraft:dead_fire_coral_block": "1.13.0",
    "minecraft:dead_horn_coral_block": "1.13.0",
    "minecraft:dried_kelp_block": "1.13.0",
    "minecraft:kelp_plant": "1.13.0",
    "minecraft:stripped_oak_log": "1.13.0",
    "minecraft:stripped_spruce_log": "1.13.0",
    "minecraft:stripped_birch_log": "1.13.0",
    "minecraft:stripped_jungle_log": "1.13.0",
    "minecraft:stripped_acacia_log": "1.13.0",
    "minecraft:stripped_dark_oak_log": "1.13.0",
    "minecraft:stripped_oak_wood": "1.13.0",
    "minecraft:stripped_spruce_wood": "1.13.0",
    "minecraft:stripped_birch_wood": "1.13.0",
    "minecraft:stripped_jungle_wood": "1.13.0",
    "minecraft:stripped_acacia_wood": "1.13.0",
    "minecraft:stripped_dark_oak_wood": "1.13.0",
    "minecraft:smooth_stone": "1.13.0",
    "minecraft:smooth_stone_slab": "1.13.0",
    "minecraft:smooth_sandstone": "1.13.0",
    "minecraft:smooth_sandstone_slab": "1.13.0",
    "minecraft:smooth_red_sandstone": "1.13.0",
    "minecraft:smooth_red_sandstone_slab": "1.13.0",
    "minecraft:smooth_quartz": "1.13.0",
    "minecraft:smooth_quartz_slab": "1.13.0",
    "minecraft:cut_sandstone_slab": "1.13.0",
    "minecraft:cut_red_sandstone_slab": "1.13.0",
    "minecraft:petrified_oak_slab": "1.13.0",

    // ========== 1.14.0 ==========
    "minecraft:diorite_slab": "1.14.0",
    "minecraft:polished_diorite_slab": "1.14.0",
    "minecraft:andesite_slab": "1.14.0",
    "minecraft:polished_andesite_slab": "1.14.0",
    "minecraft:granite_slab": "1.14.0",
    "minecraft:polished_granite_slab": "1.14.0",
    "minecraft:end_stone_brick_slab": "1.14.0",
    "minecraft:red_nether_brick_slab": "1.14.0",
    "minecraft:mossy_stone_brick_slab": "1.14.0",
    "minecraft:mossy_cobblestone_slab": "1.14.0",
    "minecraft:bamboo_block": "1.14.0",
    "minecraft:barrel": "1.14.0",
    "minecraft:blast_furnace": "1.14.0",
    "minecraft:cartography_table": "1.14.0",
    "minecraft:fletching_table": "1.14.0",
    "minecraft:grindstone": "1.14.0",
    "minecraft:lectern": "1.14.0",
    "minecraft:loom": "1.14.0",
    "minecraft:smithing_table": "1.14.0",
    "minecraft:smoker": "1.14.0",
    "minecraft:composter": "1.14.0",
    "minecraft:jigsaw": "1.14.0",

    // ========== 1.15.0 ==========
    "minecraft:bee_nest": "1.15.0",
    "minecraft:beehive": "1.15.0",
    "minecraft:honey_block": "1.15.0",
    "minecraft:honeycomb_block": "1.15.0",

    // ========== 1.16.0 ==========
    "minecraft:ancient_debris": "1.16.0",
    "minecraft:netherite_block": "1.16.0",
    "minecraft:crying_obsidian": "1.16.0",
    "minecraft:respawn_anchor": "1.16.0",
    "minecraft:basalt": "1.16.0",
    "minecraft:polished_basalt": "1.16.0",
    "minecraft:smooth_basalt": "1.16.0",
    "minecraft:soul_soil": "1.16.0",
    "minecraft:crimson_nylium": "1.16.0",
    "minecraft:warped_nylium": "1.16.0",
    "minecraft:crimson_stem": "1.16.0",
    "minecraft:warped_stem": "1.16.0",
    "minecraft:stripped_crimson_stem": "1.16.0",
    "minecraft:stripped_warped_stem": "1.16.0",
    "minecraft:crimson_hyphae": "1.16.0",
    "minecraft:warped_hyphae": "1.16.0",
    "minecraft:stripped_crimson_hyphae": "1.16.0",
    "minecraft:stripped_warped_hyphae": "1.16.0",
    "minecraft:crimson_planks": "1.16.0",
    "minecraft:warped_planks": "1.16.0",
    "minecraft:crimson_slab": "1.16.0",
    "minecraft:warped_slab": "1.16.0",
    "minecraft:crimson_pressure_plate": "1.16.0",
    "minecraft:warped_pressure_plate": "1.16.0",
    "minecraft:nether_gold_ore": "1.16.0",
    "minecraft:shroomlight": "1.16.0",
    "minecraft:lodestone": "1.16.0",
    "minecraft:target": "1.16.0",
    "minecraft:blackstone": "1.16.0",
    "minecraft:blackstone_slab": "1.16.0",
    "minecraft:polished_blackstone": "1.16.0",
    "minecraft:polished_blackstone_slab": "1.16.0",
    "minecraft:polished_blackstone_bricks": "1.16.0",
    "minecraft:polished_blackstone_brick_slab": "1.16.0",
    "minecraft:cracked_polished_blackstone_bricks": "1.16.0",
    "minecraft:chiseled_polished_blackstone": "1.16.0",
    "minecraft:gilded_blackstone": "1.16.0",
    "minecraft:polished_blackstone_pressure_plate": "1.16.0",
    "minecraft:warped_wart_block": "1.16.0",
    "minecraft:quartz_bricks": "1.16.0",
    "minecraft:chain": "1.16.0",
    "minecraft:chiseled_nether_bricks": "1.16.0",
    "minecraft:cracked_nether_bricks": "1.16.0",

    // ========== 1.17.0 ==========
    "minecraft:copper_ore": "1.17.0",
    "minecraft:copper_block": "1.17.0",
    "minecraft:cut_copper": "1.17.0",
    "minecraft:cut_copper_slab": "1.17.0",
    "minecraft:exposed_copper": "1.17.0",
    "minecraft:exposed_cut_copper": "1.17.0",
    "minecraft:exposed_cut_copper_slab": "1.17.0",
    "minecraft:weathered_copper": "1.17.0",
    "minecraft:weathered_cut_copper": "1.17.0",
    "minecraft:weathered_cut_copper_slab": "1.17.0",
    "minecraft:oxidized_copper": "1.17.0",
    "minecraft:oxidized_cut_copper": "1.17.0",
    "minecraft:oxidized_cut_copper_slab": "1.17.0",
    "minecraft:waxed_copper_block": "1.17.0",
    "minecraft:waxed_cut_copper": "1.17.0",
    "minecraft:waxed_cut_copper_slab": "1.17.0",
    "minecraft:waxed_exposed_copper": "1.17.0",
    "minecraft:waxed_exposed_cut_copper": "1.17.0",
    "minecraft:waxed_exposed_cut_copper_slab": "1.17.0",
    "minecraft:waxed_weathered_copper": "1.17.0",
    "minecraft:waxed_weathered_cut_copper": "1.17.0",
    "minecraft:waxed_weathered_cut_copper_slab": "1.17.0",
    "minecraft:waxed_oxidized_copper": "1.17.0",
    "minecraft:waxed_oxidized_cut_copper": "1.17.0",
    "minecraft:waxed_oxidized_cut_copper_slab": "1.17.0",
    "minecraft:raw_copper_block": "1.17.0",
    "minecraft:raw_iron_block": "1.17.0",
    "minecraft:raw_gold_block": "1.17.0",
    "minecraft:deepslate": "1.17.0",
    "minecraft:cobbled_deepslate": "1.17.0",
    "minecraft:cobbled_deepslate_slab": "1.17.0",
    "minecraft:polished_deepslate": "1.17.0",
    "minecraft:polished_deepslate_slab": "1.17.0",
    "minecraft:deepslate_bricks": "1.17.0",
    "minecraft:deepslate_brick_slab": "1.17.0",
    "minecraft:deepslate_tiles": "1.17.0",
    "minecraft:deepslate_tile_slab": "1.17.0",
    "minecraft:chiseled_deepslate": "1.17.0",
    "minecraft:cracked_deepslate_bricks": "1.17.0",
    "minecraft:cracked_deepslate_tiles": "1.17.0",
    "minecraft:deepslate_coal_ore": "1.17.0",
    "minecraft:deepslate_iron_ore": "1.17.0",
    "minecraft:deepslate_copper_ore": "1.17.0",
    "minecraft:deepslate_gold_ore": "1.17.0",
    "minecraft:deepslate_redstone_ore": "1.17.0",
    "minecraft:deepslate_emerald_ore": "1.17.0",
    "minecraft:deepslate_lapis_ore": "1.17.0",
    "minecraft:deepslate_diamond_ore": "1.17.0",
    "minecraft:tuff": "1.17.0",
    "minecraft:calcite": "1.17.0",
    "minecraft:amethyst_block": "1.17.0",
    "minecraft:budding_amethyst": "1.17.0",
    "minecraft:powder_snow": "1.17.0",
    "minecraft:tinted_glass": "1.17.0",
    "minecraft:dripstone_block": "1.17.0",
    "minecraft:rooted_dirt": "1.17.0",
    "minecraft:moss_block": "1.17.0",
    "minecraft:moss_carpet": "1.17.0",
    "minecraft:azalea_leaves": "1.17.0",
    "minecraft:flowering_azalea_leaves": "1.17.0",
    "minecraft:glow_lichen": "1.17.0",
    "minecraft:candle": "1.17.0",
    "minecraft:white_candle": "1.17.0",
    "minecraft:orange_candle": "1.17.0",
    "minecraft:magenta_candle": "1.17.0",
    "minecraft:light_blue_candle": "1.17.0",
    "minecraft:yellow_candle": "1.17.0",
    "minecraft:lime_candle": "1.17.0",
    "minecraft:pink_candle": "1.17.0",
    "minecraft:gray_candle": "1.17.0",
    "minecraft:light_gray_candle": "1.17.0",
    "minecraft:cyan_candle": "1.17.0",
    "minecraft:purple_candle": "1.17.0",
    "minecraft:blue_candle": "1.17.0",
    "minecraft:brown_candle": "1.17.0",
    "minecraft:green_candle": "1.17.0",
    "minecraft:red_candle": "1.17.0",
    "minecraft:black_candle": "1.17.0",

    // ========== 1.18.0 ==========
    "minecraft:infested_deepslate": "1.18.0",

    // ========== 1.19.0 ==========
    "minecraft:mangrove_log": "1.19.0",
    "minecraft:mangrove_wood": "1.19.0",
    "minecraft:mangrove_planks": "1.19.0",
    "minecraft:mangrove_slab": "1.19.0",
    "minecraft:mangrove_leaves": "1.19.0",
    "minecraft:mangrove_roots": "1.19.0",
    "minecraft:muddy_mangrove_roots": "1.19.0",
    "minecraft:stripped_mangrove_log": "1.19.0",
    "minecraft:stripped_mangrove_wood": "1.19.0",
    "minecraft:mangrove_pressure_plate": "1.19.0",
    "minecraft:mud": "1.19.0",
    "minecraft:packed_mud": "1.19.0",
    "minecraft:mud_bricks": "1.19.0",
    "minecraft:mud_brick_slab": "1.19.0",
    "minecraft:sculk": "1.19.0",
    "minecraft:sculk_catalyst": "1.19.0",
    "minecraft:sculk_shrieker": "1.19.0",
    "minecraft:sculk_vein": "1.19.0",
    "minecraft:reinforced_deepslate": "1.19.0",
    "minecraft:ochre_froglight": "1.19.0",
    "minecraft:pearlescent_froglight": "1.19.0",
    "minecraft:verdant_froglight": "1.19.0",

    // ========== 1.20.0 ==========
    "minecraft:bamboo_planks": "1.20.0",
    "minecraft:bamboo_slab": "1.20.0",
    "minecraft:bamboo_mosaic": "1.20.0",
    "minecraft:bamboo_mosaic_slab": "1.20.0",
    "minecraft:stripped_bamboo_block": "1.20.0",
    "minecraft:bamboo_pressure_plate": "1.20.0",
    "minecraft:chiseled_bookshelf": "1.20.0",
    "minecraft:cherry_log": "1.20.0",
    "minecraft:cherry_wood": "1.20.0",
    "minecraft:cherry_planks": "1.20.0",
    "minecraft:cherry_slab": "1.20.0",
    "minecraft:cherry_leaves": "1.20.0",
    "minecraft:stripped_cherry_log": "1.20.0",
    "minecraft:stripped_cherry_wood": "1.20.0",
    "minecraft:cherry_pressure_plate": "1.20.0",
    "minecraft:decorated_pot": "1.20.0",
    "minecraft:suspicious_sand": "1.20.0",
    "minecraft:suspicious_gravel": "1.20.0",
    "minecraft:pitcher_plant": "1.20.0",

    // ========== 1.21.0 ==========
    "minecraft:tuff_slab": "1.21.0",
    "minecraft:polished_tuff": "1.21.0",
    "minecraft:polished_tuff_slab": "1.21.0",
    "minecraft:tuff_bricks": "1.21.0",
    "minecraft:tuff_brick_slab": "1.21.0",
    "minecraft:chiseled_tuff": "1.21.0",
    "minecraft:chiseled_tuff_bricks": "1.21.0",
    "minecraft:chiseled_copper": "1.21.0",
    "minecraft:exposed_chiseled_copper": "1.21.0",
    "minecraft:weathered_chiseled_copper": "1.21.0",
    "minecraft:oxidized_chiseled_copper": "1.21.0",
    "minecraft:waxed_chiseled_copper": "1.21.0",
    "minecraft:waxed_exposed_chiseled_copper": "1.21.0",
    "minecraft:waxed_weathered_chiseled_copper": "1.21.0",
    "minecraft:waxed_oxidized_chiseled_copper": "1.21.0",
    "minecraft:copper_bulb": "1.21.0",
    "minecraft:exposed_copper_bulb": "1.21.0",
    "minecraft:weathered_copper_bulb": "1.21.0",
    "minecraft:oxidized_copper_bulb": "1.21.0",
    "minecraft:waxed_copper_bulb": "1.21.0",
    "minecraft:waxed_exposed_copper_bulb": "1.21.0",
    "minecraft:waxed_weathered_copper_bulb": "1.21.0",
    "minecraft:waxed_oxidized_copper_bulb": "1.21.0",
    "minecraft:copper_grate": "1.21.0",
    "minecraft:exposed_copper_grate": "1.21.0",
    "minecraft:weathered_copper_grate": "1.21.0",
    "minecraft:oxidized_copper_grate": "1.21.0",
    "minecraft:waxed_copper_grate": "1.21.0",
    "minecraft:waxed_exposed_copper_grate": "1.21.0",
    "minecraft:waxed_weathered_copper_grate": "1.21.0",
    "minecraft:waxed_oxidized_copper_grate": "1.21.0",
    "minecraft:trial_spawner": "1.21.0",
    "minecraft:vault": "1.21.0",
    "minecraft:heavy_core": "1.21.0",
    "minecraft:crafter": "1.21.0",

    // ========== 1.21.4 (Pale Garden) ==========
    "minecraft:pale_oak_log": "1.21.4",
    "minecraft:pale_oak_wood": "1.21.4",
    "minecraft:pale_oak_planks": "1.21.4",
    "minecraft:pale_oak_slab": "1.21.4",
    "minecraft:pale_oak_leaves": "1.21.4",
    "minecraft:stripped_pale_oak_log": "1.21.4",
    "minecraft:stripped_pale_oak_wood": "1.21.4",
    "minecraft:pale_oak_pressure_plate": "1.21.4",
    "minecraft:pale_moss_block": "1.21.4",
    "minecraft:resin_block": "1.21.4",
    "minecraft:resin_bricks": "1.21.4",
    "minecraft:resin_brick_slab": "1.21.4",
    "minecraft:chiseled_resin_bricks": "1.21.4",
    "minecraft:resin_clump": "1.21.4",
    "minecraft:creaking_heart": "1.21.4",

    // ========== 1.21.5 ==========
    "minecraft:firefly_bush": "1.21.5",
    "minecraft:test_block": "1.21.5",
};

// Types for the palette
interface Block {
    id: string;
    needsSupport: boolean;
    introducedIn?: string;
}

interface Color {
    colorID: number;
    colorName: string;
    blocks: Block[];
}

interface Palette {
    version: string;
    colors: Color[];
}

const main = () => {
    const palettePath = path.resolve(process.cwd(), "./src/data/palette.json");

    if (!fs.existsSync(palettePath)) {
        console.error(`Palette file not found at: ${palettePath}`);
        process.exit(1);
    }

    const palette: Palette = JSON.parse(fs.readFileSync(palettePath, "utf8"));

    // Keep track of missing blocks
    const missingBlocks = new Set<string>();

    // Add introducedIn to each block
    palette.colors.forEach((color) => {
        color.blocks.forEach((block) => {
            const version = blockVersions[block.id];
            if (version) {
                block.introducedIn = version;
            } else {
                // Default legacy blocks to 1.0.0
                block.introducedIn = "1.0.0";
                missingBlocks.add(block.id);
            }
        });
    });

    // Write the updated palette
    fs.writeFileSync(palettePath, JSON.stringify(palette, null, 2));

    console.log("Palette updated successfully!");
    console.log(`Total colors: ${palette.colors.length}`);
    console.log(
        `Blocks defaulted to 1.0.0 (may need review): ${missingBlocks.size}`,
    );
    if (missingBlocks.size > 0) {
        console.log("Missing blocks:");
        Array.from(missingBlocks).sort().forEach((b) => console.log(`  ${b}`));
    }
};

main();
